### ISSUE TITLE
acc = 0.0, how to fix it?

### ISSUE THREAD

**Issue by star5o** [Ecohnoch/Vggvox-TensorFlow#2]
counter:  33000 loss_val 6.795684 acc:  0.0
counter:  33100 loss_val 7.0046344 acc:  0.0
counter:  33200 loss_val 7.1294093 acc:  0.0
counter:  33300 loss_val 7.397499 acc:  0.0
counter:  33400 loss_val 6.5734997 acc:  0.0
counter:  33500 loss_val 7.1563115 acc:  0.0
counter:  33600 loss_val 6.9506817 acc:  0.0
counter:  33700 loss_val 6.953585 acc:  0.0
counter:  33800 loss_val 6.579544 acc:  0.0
counter:  33900 loss_val 6.658001 acc:  0.0
counter:  34000 loss_val 6.848481 acc:  0.0
counter:  34100 loss_val 6.7837143 acc:  0.0
counter:  34200 loss_val 6.8467336 acc:  0.0
counter:  34300 loss_val 6.770242 acc:  0.0
counter:  34400 loss_val 6.7377167 acc:  0.0625
counter:  34500 loss_val 6.7753534 acc:  0.0
counter:  34600 loss_val 7.1262016 acc:  0.0
counter:  34700 loss_val 6.9896407 acc:  0.0

**Comment by Finn-Fengming** [comment]
Sorry for my late reply. I updated the codes and train this version.
